apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ template "dshopCacheStorage.fullname" . }}"
  labels:
    {{- include "dshop.selectorLabels" . | nindent 8 }}
spec:
 accessModes:
 - ReadWriteMany
 storageClassName: ""
 volumeName: {{ template "dshopCacheStorage.fullname" . }}
 resources:
   requests:
     storage: {{ default "50Gi" .Values.dshopCacheStorageRequestSize }}
