apiVersion: v1
kind: Service
metadata:
  name: {{ template "dshop.fullname" . }}-balancer
  labels:
    {{- include "dshop.selectorLabels" . | nindent 8 }}
spec:
  type: LoadBalancer
  selector:
    {{- include "dshop.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 3000
