apiVersion: v1
kind: Service
metadata:
  name: {{ template "issuer.fullname" . }}
  labels:
    {{- include "dshop.selectorLabels" . | nindent 8 }}
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.dshopIssuerIp }}
  selector:
    app: {{ template "issuer.fullname" . }}
  ports:
  - name: http
    port: 80
  - name: https
    port: 443
