apiVersion: v1
kind: Service
metadata:
  name: {{ template "dshopRedis.fullname" . }}
  labels:
    {{- include "dshop.selectorLabels" . | nindent 8 }}
spec:
  clusterIP: None
  selector:
    app: {{ template "dshopRedis.fullname" . }}
  ports:
  - name: redis
    port: 6379
  - name: gossip
    port: 16379
