releases:
  - name: "dshop-{{ .Environment.Name }}"
    namespace: default
    chart: charts/dshop
    values:
      - charts/dshop/values.yaml
      - values/dshop/{{ .Environment.Name }}.yaml
      - environment: "{{ .Environment.Name }}"
    secrets:
      - values/dshop/secrets.{{ .Environment.Name }}.yaml

  # This is only one deployment, but the sync will happen
  # for every environment
  - name: prometheus-operator
    namespace: monitoring
    chart: prometheus-community/prometheus-operator
    values:
      - values/monitoring/values.yaml
    secrets:
      - values/monitoring/secrets.yaml
missingFileHandler: Error
# The below values are NOT CHART VALUES, it's weird. They seem to
# be only values you can use here in this helmfile.  The regular
# chart values are added here just to be accessible and future
# reference but aren't used currently.
environments:
  # default env is only used in linting
  default:
    values:
      - charts/dshop/values.yaml
      - dshopVersion: latest
  mainnet:
    values:
      - charts/dshop/values.yaml
      - dshopVersion: 2021021721071613596036
  rinkeby:
    values:
      - charts/dshop/values.yaml
      - dshopVersion: 2021021721071613596020
